In [147]:
import pandas as pd

In [148]:
plan = pd.read_csv('player_totals.csv')
plan

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,31871.0,2025,5025.0,A.J. Green,NaN,SG,25.0,3.0,NBA,MIL,...,0.833,16.0,134.0,150.0,97,36.0,6.0,37.0,144,486
1,31872.0,2025,5026.0,A.J. Lawson,NaN,SG,24.0,3.0,NBA,TOR,...,0.647,13.0,44.0,57.0,16,6.0,4.0,8.0,29,148
2,31873.0,2025,5210.0,AJ Johnson,NaN,SG,20.0,1.0,NBA,TOT,...,0.840,7.0,37.0,44.0,52,9.0,2.0,23.0,20,141
3,31874.0,2025,5210.0,AJ Johnson,NaN,SG,20.0,1.0,NBA,MIL,...,0.500,0.0,7.0,7.0,7,1.0,0.0,4.0,0,20
4,31875.0,2025,5210.0,AJ Johnson,NaN,SG,20.0,1.0,NBA,WAS,...,0.870,7.0,30.0,37.0,45,8.0,2.0,19.0,20,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32584,200.0,1947,157.0,Walt Miller,NaN,F,31.0,1.0,BAA,PIT,...,0.500,NaN,NaN,NaN,6,NaN,NaN,NaN,16,23
32585,201.0,1947,158.0,Warren Fenley,NaN,F,24.0,1.0,BAA,BOS,...,0.511,NaN,NaN,NaN,16,NaN,NaN,NaN,59,85
32586,202.0,1947,159.0,Wilbert Kautz,NaN,G-F,31.0,1.0,BAA,CHS,...,0.534,NaN,NaN,NaN,37,NaN,NaN,NaN,114,253
32587,203.0,1947,160.0,Woody Grimshaw,NaN,G,27.0,1.0,BAA,PRO,...,0.477,NaN,NaN,NaN,1,NaN,NaN,NaN,25,61
32588,204.0,1947,161.0,Wyndol Gray,NaN,G-F,24.0,1.0,BAA,BOS,...,0.581,NaN,NaN,NaN,47,NaN,NaN,NaN,105,350

In [149]:
plan.loc[plan['player'] == 'Gui Santos']

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb,drb,trb,ast,stl,blk,tov,pf,pts
238,32109.0,2025,5144.0,Gui Santos,NaN,PF,22.0,2.0,NBA,GSW,...,0.694,59.0,92.0,151.0,70,21.0,9.0,37.0,80,214
960,31377.0,2024,5144.0,Gui Santos,NaN,PF,21.0,1.0,NBA,GSW,...,0.941,17.0,32.0,49.0,14,4.0,2.0,7.0,23,82

### Excluindo coluna que tem todos os valores nulos

In [150]:
plan.isnull()

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,ft_percent,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32584,False,False,False,False,True,False,False,False,False,False,...,False,True,True,True,False,True,True,True,False,False
32585,False,False,False,False,True,False,False,False,False,False,...,False,True,True,True,False,True,True,True,False,False
32586,False,False,False,False,True,False,False,False,False,False,...,False,True,True,True,False,True,True,True,False,False
32587,False,False,False,False,True,False,False,False,False,False,...,False,True,True,True,False,True,True,True,False,False
32588,False,False,False,False,True,False,False,False,False,False,...,False,True,True,True,False,True,True,True,False,False

In [151]:
plan.drop('birth_year', axis=1)

,seas_id,season,player_id,player,pos,age,experience,lg,tm,g,...,ft_percent,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,31871.0,2025,5025.0,A.J. Green,SG,25.0,3.0,NBA,MIL,66,...,0.833,16.0,134.0,150.0,97,36.0,6.0,37.0,144,486
1,31872.0,2025,5026.0,A.J. Lawson,SG,24.0,3.0,NBA,TOR,19,...,0.647,13.0,44.0,57.0,16,6.0,4.0,8.0,29,148
2,31873.0,2025,5210.0,AJ Johnson,SG,20.0,1.0,NBA,TOT,22,...,0.840,7.0,37.0,44.0,52,9.0,2.0,23.0,20,141
3,31874.0,2025,5210.0,AJ Johnson,SG,20.0,1.0,NBA,MIL,7,...,0.500,0.0,7.0,7.0,7,1.0,0.0,4.0,0,20
4,31875.0,2025,5210.0,AJ Johnson,SG,20.0,1.0,NBA,WAS,15,...,0.870,7.0,30.0,37.0,45,8.0,2.0,19.0,20,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32584,200.0,1947,157.0,Walt Miller,F,31.0,1.0,BAA,PIT,12,...,0.500,NaN,NaN,NaN,6,NaN,NaN,NaN,16,23
32585,201.0,1947,158.0,Warren Fenley,F,24.0,1.0,BAA,BOS,33,...,0.511,NaN,NaN,NaN,16,NaN,NaN,NaN,59,85
32586,202.0,1947,159.0,Wilbert Kautz,G-F,31.0,1.0,BAA,CHS,50,...,0.534,NaN,NaN,NaN,37,NaN,NaN,NaN,114,253
32587,203.0,1947,160.0,Woody Grimshaw,G,27.0,1.0,BAA,PRO,21,...,0.477,NaN,NaN,NaN,1,NaN,NaN,NaN,25,61
32588,204.0,1947,161.0,Wyndol Gray,G-F,24.0,1.0,BAA,BOS,55,...,0.581,NaN,NaN,NaN,47,NaN,NaN,NaN,105,350

### Verificando se há duplicatas

In [152]:
print(plan.duplicated())

0        False
1        False
2        False
3        False
4        False
         ...
32584    False
32585    False
32586    False
32587    False
32588    False
Length: 32589, dtype: bool

## 3. Análise descritiva

### 3.1 Quantos jogadores únicos existem na base?

In [153]:
qtd_jogadores_unicos = plan['player'].nunique()
jogadores_unicos = plan['player'].unique()
print(qtd_jogadores_unicos)
jogadores_unicos

5264

array(['A.J. Green', 'A.J. Lawson', 'AJ Johnson', ..., 'Warren Fenley',
       'Wilbert Kautz', 'Woody Grimshaw'], dtype=object)

## 3.2 Média de pontos, reb e ast's por player

In [154]:
pts = plan.groupby('player')['pts'].mean()
pts

player
A.C. Green              718.222222
A.J. Bramlett             8.000000
A.J. English            751.000000
A.J. Green              297.333333
A.J. Guyton             147.333333
                           ...
Šarūnas Marčiulionis    661.571429
Žan Tabak               192.500000
Žarko Paspalj            72.000000
Žarko Čabarkapa         175.600000
Željko Rebrača          195.285714
Name: pts, Length: 5264, dtype: float64

In [155]:
ast = plan.groupby('player')['ast'].mean()
ast

player
A.C. Green               81.611111
A.J. Bramlett             0.000000
A.J. English            160.000000
A.J. Green               49.666667
A.J. Guyton              49.000000
                           ...
Šarūnas Marčiulionis    115.285714
Žan Tabak                26.625000
Žarko Paspalj            10.000000
Žarko Čabarkapa          22.000000
Željko Rebrača           13.428571
Name: ast, Length: 5264, dtype: float64

In [156]:
trb = plan.groupby('player')['trb'].mean()
trb

player
A.C. Green              562.722222
A.J. Bramlett            22.000000
A.J. English            157.500000
A.J. Green               86.333333
A.J. Guyton              26.666667
                           ...
Šarūnas Marčiulionis    117.000000
Žan Tabak               136.875000
Žarko Paspalj            30.000000
Žarko Čabarkapa          82.800000
Željko Rebrača          106.571429
Name: trb, Length: 5264, dtype: float64

### 3.3 Quem é o jogador com mais pontos totais na temporada

In [157]:
temporada = plan[plan['season'] == 2025]
mais_pontos = temporada.loc[temporada['pts'].idxmax()]
mais_pontos

seas_id                         32489.0
season                             2025
player_id                        4669.0
player          Shai Gilgeous-Alexander
birth_year                          NaN
pos                                  PG
age                                26.0
experience                          7.0
lg                                  NBA
tm                                  OKC
g                                    72
gs                                 72.0
mp                               2460.0
fg                                  814
fga                                1559
fg_percent                        0.522
x3p                               153.0
x3pa                              408.0
x3p_percent                       0.375
x2p                                 661
x2pa                               1151
x2p_percent                       0.574
e_fg_percent                      0.571
ft                                  580
fta                                 644
ft_percent                        0.901
orb                                63.0
drb                               297.0
trb                               360.0
ast                                 460
stl                               124.0
blk                                73.0
tov                               177.0
pf                                  155
pts                                2361
Name: 618, dtype: object

In [158]:
mais_pontos[['player', 'pts']]

player    Shai Gilgeous-Alexander
pts                          2361
Name: 618, dtype: object

### 3.4 Descobrindo o jogador com o maior PPG

In [159]:
plan['ppg'] = plan['pts'] / plan['g']

In [160]:
ppg = plan.loc[plan['ppg'].idxmax()]
ppg

seas_id                   2445.0
season                      1962
player_id                  699.0
player          Wilt Chamberlain
birth_year                   NaN
pos                            C
age                         25.0
experience                   3.0
lg                           NBA
tm                           PHW
g                             80
gs                           NaN
mp                        3882.0
fg                          1597
fga                         3159
fg_percent                 0.506
x3p                          NaN
x3pa                         NaN
x3p_percent                  NaN
x2p                         1597
x2pa                        3159
x2p_percent                0.506
e_fg_percent               0.506
ft                           835
fta                         1363
ft_percent                 0.613
orb                          NaN
drb                          NaN
trb                       2052.0
ast                          192
stl                          NaN
blk                          NaN
tov                          NaN
pf                           123
pts                         4029
ppg                      50.3625
Name: 30267, dtype: object

## 4. Ranking

### 4.1 Top 10 jogadores com mais ast na temporada

In [161]:
ast_df_temp = temporada.groupby('player')['ast'].sum()
ast_df_temp = pd.DataFrame(ast_df_temp)
ast_df_temp

                 ast
player
A.J. Green        97
A.J. Lawson       16
AJ Johnson       104
Aaron Gordon     139
Aaron Holiday     70
...              ...
Zach LaVine      564
Zeke Nnaji        21
Ziaire Williams   82
Zion Williamson  159
Zyon Pullin        0

[563 rows x 1 columns]

In [162]:
# ast_df_temp.nlargest(10, 'ast', keep='first')
ast_df_temp.sort_values(by='ast', ascending=False).head(10)

                   ast
player
Trae Young         796
De'Aaron Fox       784
Dennis Schröder    750
Luka Dončić        692
Nikola Jokić       653
Davion Mitchell    632
Tyrese Haliburton  622
James Harden       616
Cade Cunningham    609
D'Angelo Russell   592

### 4.2 Jogadores com mais rebotes na temporada

In [163]:
reb_df_temp = temporada.groupby('player')['trb'].sum()
reb_df_temp = pd.DataFrame(reb_df_temp)
reb_df_temp

                   trb
player
A.J. Green       150.0
A.J. Lawson       57.0
AJ Johnson        88.0
Aaron Gordon     219.0
Aaron Holiday     70.0
...                ...
Zach LaVine      588.0
Zeke Nnaji        86.0
Ziaire Williams  278.0
Zion Williamson  216.0
Zyon Pullin        0.0

[563 rows x 1 columns]

In [164]:
reb_df_temp.sort_values(by='trb', ascending=False).head(10)

                       trb
player
Jonas Valančiūnas   1170.0
Anthony Davis       1084.0
Ivica Zubac          918.0
Domantas Sabonis     881.0
Nick Richards        874.0
Karl-Anthony Towns   859.0
Nikola Jokić         820.0
Alperen Şengün       751.0
Jarrett Allen        749.0
Luka Dončić          738.0

## 5. Análise por time

### 5.1 Total de pontos dos times na temporada

In [165]:
pontos_time = temporada.groupby(['tm'])['pts'].sum()
pontos_time = pd.DataFrame(pontos_time)
pontos_time

       pts
tm
ATL   8722
BOS   8766
BRK   7996
CHI   8801
CHO   7918
CLE   9175
DAL   8731
DEN   9066
DET   8664
GSW   8394
HOU   8661
IND   8781
LAC   8412
LAL   8479
MEM   9146
MIA   8223
MIL   8470
MIN   8536
NOP   8264
NYK   8613
OKC   9031
ORL   7971
PHI   8236
PHO   8571
POR   8300
SAC   8682
SAS   8448
TOR   8299
TOT  27966
UTA   8475
WAS   8144

### 5.2 Listar os 5 times com mais pontos

In [166]:
top5_pontos_time = pontos_time.sort_values(by='pts', ascending=False).head(6)
top5_pontos_time

       pts
tm
TOT  27966
CLE   9175
MEM   9146
DEN   9066
OKC   9031
CHI   8801

## 6. Coluna de Eficiência

#### *Fórmula (pts + reb + ast) / partidas

In [167]:
plan['eff'] = (plan['pts'] + plan['trb'] + plan['ast']) / plan['g']
plan = pd.DataFrame(plan)
plan

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,...,drb,trb,ast,stl,blk,tov,pf,pts,ppg,eff
0,31871.0,2025,5025.0,A.J. Green,NaN,SG,25.0,3.0,NBA,MIL,...,134.0,150.0,97,36.0,6.0,37.0,144,486,7.363636,11.106061
1,31872.0,2025,5026.0,A.J. Lawson,NaN,SG,24.0,3.0,NBA,TOR,...,44.0,57.0,16,6.0,4.0,8.0,29,148,7.789474,11.631579
2,31873.0,2025,5210.0,AJ Johnson,NaN,SG,20.0,1.0,NBA,TOT,...,37.0,44.0,52,9.0,2.0,23.0,20,141,6.409091,10.772727
3,31874.0,2025,5210.0,AJ Johnson,NaN,SG,20.0,1.0,NBA,MIL,...,7.0,7.0,7,1.0,0.0,4.0,0,20,2.857143,4.857143
4,31875.0,2025,5210.0,AJ Johnson,NaN,SG,20.0,1.0,NBA,WAS,...,30.0,37.0,45,8.0,2.0,19.0,20,121,8.066667,13.533333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32584,200.0,1947,157.0,Walt Miller,NaN,F,31.0,1.0,BAA,PIT,...,NaN,NaN,6,NaN,NaN,NaN,16,23,1.916667,NaN
32585,201.0,1947,158.0,Warren Fenley,NaN,F,24.0,1.0,BAA,BOS,...,NaN,NaN,16,NaN,NaN,NaN,59,85,2.575758,NaN
32586,202.0,1947,159.0,Wilbert Kautz,NaN,G-F,31.0,1.0,BAA,CHS,...,NaN,NaN,37,NaN,NaN,NaN,114,253,5.060000,NaN
32587,203.0,1947,160.0,Woody Grimshaw,NaN,G,27.0,1.0,BAA,PRO,...,NaN,NaN,1,NaN,NaN,NaN,25,61,2.904762,NaN
32588,204.0,1947,161.0,Wyndol Gray,NaN,G-F,24.0,1.0,BAA,BOS,...,NaN,NaN,47,NaN,NaN,NaN,105,350,6.363636,NaN

In [168]:
top5eff = plan.groupby('player')['eff'].sum()
top5eff = pd.DataFrame(top5eff)
top5eff

                             eff
player
A.C. Green            316.908831
A.J. Bramlett           3.750000
A.J. English           28.206349
A.J. Green             23.598918
A.J. Guyton            18.230303
...                          ...
Šarūnas Marčiulionis  117.334684
Žan Tabak              69.156862
Žarko Paspalj           4.000000
Žarko Čabarkapa        35.054968
Željko Rebrača         62.094463

[5264 rows x 1 columns]

In [169]:
top5eff = plan.sort_values('eff', ascending=False).head(5)[['player', 'eff']]
top5eff

                 player        eff
30267  Wilt Chamberlain  78.412500
30133  Wilt Chamberlain  72.587500
30375  Wilt Chamberlain  67.468354
30498  Wilt Chamberlain  66.888889
29867  Wilt Chamberlain  65.526316

In [172]:
plan.to_csv('player_totals_ex.csv', index=False)